# golangci-lint configuration
# Run with: golangci-lint run

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - third_party
    - testdata
    - examples
    - .git
  skip-files:
    - ".*\\.pb\\.go$"
    - ".*\\.gen\\.go$"

linters:
  enable:
    # Default linters
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    
    # Additional linters for code quality
    - bodyclose
    - contextcheck
    - durationcheck
    - errorlint
    - exhaustive
    - exportloopref
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gosec
    - misspell
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - sqlclosecheck
    - unconvert
    - unparam
    - whitespace

  disable:
    - depguard # Too restrictive
    - dupl # Too many false positives
    - gochecknoglobals # We use some globals
    - lll # Line length is handled by editor
    - wsl # Too opinionated about whitespace

linters-settings:
  gocyclo:
    min-complexity: 15
    
  goconst:
    min-len: 3
    min-occurrences: 3
    
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - whyNoLint
      
  gofmt:
    simplify: true
    
  goimports:
    local-prefixes: github.com/database-intelligence
    
  gosec:
    excludes:
      - G104 # We handle errors appropriately
    config:
      G301: "0750" # Expect stricter file permissions
      
  govet:
    check-shadowing: true
    enable-all: true
    
  misspell:
    locale: US
    
  nolintlint:
    allow-leading-space: false
    require-explanation: true
    require-specific: true
    
  revive:
    ignore-generated-header: true
    severity: warning
    
  staticcheck:
    checks: ["all"]
    
issues:
  exclude-rules:
    # Exclude some linters from test files
    - path: _test\.go
      linters:
        - gosec
        - dupl
        - goconst
        
    # Exclude error checks in deferred calls
    - source: "defer .*\\.Close"
      linters:
        - errcheck
        
    # Allow fmt.Printf in tools
    - path: tools/
      linters:
        - forbidigo
        
  # Maximum issues count per one linter
  max-issues-per-linter: 50
  
  # Maximum count of issues with the same text
  max-same-issues: 10
  
  # Show only new issues
  new: false
  
  # Fix found issues (if it's supported by the linter)
  fix: true