dist:
  name: database-intelligence-collector
  description: Database Intelligence Collector with all standard and custom components
  output_path: ./distributions/production
  otelcol_version: 0.105.0
  version: 2.0.0
  
# Build configuration
build_info:
  description: "Database Intelligence OpenTelemetry Collector"
  version: "2.0.0"

# Standard Extensions
extensions:
  # Core extensions
  - gomod: go.opentelemetry.io/collector/extension/zpagesextension v0.105.0
  # Ballast extension is deprecated - use memory_limiter processor instead
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckextension v0.105.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/pprofextension v0.105.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/filestorage v0.105.0
  
  # Authentication extensions
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/basicauthextension v0.105.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/bearertokenauthextension v0.105.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/oauth2clientauthextension v0.105.0
  
  # Custom extensions
  # - gomod: github.com/deepaksharma/db-otel/components/extensions/healthcheck v0.0.0
  #   path: ./components/extensions/healthcheck

# Standard Receivers
receivers:
  # Core receivers
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.105.0
  
  # Database receivers
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/postgresqlreceiver v0.105.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/mysqlreceiver v0.105.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/sqlqueryreceiver v0.105.0
  
  # System receivers
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/hostmetricsreceiver v0.105.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/dockerstatsreceiver v0.105.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/k8sclusterreceiver v0.105.0
  
  # Prometheus receiver for scraping
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusreceiver v0.105.0
  
  # Custom receivers
  - gomod: github.com/deepaksharma/db-otel/components/receivers/ash v0.0.0
    path: ./components/receivers/ash
  - gomod: github.com/deepaksharma/db-otel/components/receivers/kernelmetrics v0.0.0
    path: ./components/receivers/kernelmetrics
  - gomod: github.com/deepaksharma/db-otel/components/receivers/enhancedsql v0.0.0
    path: ./components/receivers/enhancedsql

# Standard Processors
processors:
  # Core processors
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.105.0
  - gomod: go.opentelemetry.io/collector/processor/memorylimiterprocessor v0.105.0
  
  # Resource and attribute processors
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/attributesprocessor v0.105.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourceprocessor v0.105.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourcedetectionprocessor v0.105.0
  
  # Data manipulation processors
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/filterprocessor v0.105.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/transformprocessor v0.105.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/metricstransformprocessor v0.105.0
  
  # Sampling processors
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/tailsamplingprocessor v0.105.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/probabilisticsamplerprocessor v0.105.0
  
  # Grouping and routing
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/groupbyattrsprocessor v0.105.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/routingprocessor v0.105.0
  
  # Custom processors
  - gomod: github.com/deepaksharma/db-otel/components/processors/adaptivesampler v0.0.0
    path: ./components/processors/adaptivesampler
  - gomod: github.com/deepaksharma/db-otel/components/processors/circuitbreaker v0.0.0
    path: ./components/processors/circuitbreaker
  - gomod: github.com/deepaksharma/db-otel/components/processors/costcontrol v0.0.0
    path: ./components/processors/costcontrol
  - gomod: github.com/deepaksharma/db-otel/components/processors/nrerrormonitor v0.0.0
    path: ./components/processors/nrerrormonitor
  - gomod: github.com/deepaksharma/db-otel/components/processors/planattributeextractor v0.0.0
    path: ./components/processors/planattributeextractor
  - gomod: github.com/deepaksharma/db-otel/components/processors/querycorrelator v0.0.0
    path: ./components/processors/querycorrelator
  - gomod: github.com/deepaksharma/db-otel/components/processors/verification v0.0.0
    path: ./components/processors/verification

# Standard Exporters
exporters:
  # Core exporters
  - gomod: go.opentelemetry.io/collector/exporter/loggingexporter v0.105.0
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.105.0
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.105.0
  - gomod: go.opentelemetry.io/collector/exporter/otlphttpexporter v0.105.0
  
  # Monitoring exporters
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter v0.105.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusremotewriteexporter v0.105.0
  
  # File exporters
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/fileexporter v0.105.0
  
  # Queue exporters
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/kafkaexporter v0.105.0
  
  # Custom exporters
  # - gomod: github.com/deepaksharma/db-otel/components/exporters/nri v0.0.0
  #   path: ./components/exporters/nri

# Connectors for pipeline-to-pipeline data flow
connectors:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/connector/countconnector v0.105.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/connector/spanmetricsconnector v0.105.0

# Replace directives for local development
replaces:
  - github.com/deepaksharma/db-otel/components => ./components
  - github.com/deepaksharma/db-otel/common => ./common
  - github.com/deepaksharma/db-otel/internal => ./internal