# Alert Manager - Simple Configuration
# Basic alert aggregation

receivers:
  # OTLP receiver for receiving alerts
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  # Memory management
  memory_limiter:
    check_interval: 5s
    limit_percentage: 80
    spike_limit_percentage: 30
  
  batch:
    timeout: 10s
    send_batch_size: 1000
  
  # Add module attributes
  attributes:
    actions:
      - key: module
        value: alert-manager
        action: insert
      - key: environment
        value: ${env:ENVIRONMENT:-production}
        action: insert
  
  # Resource processor
  resource:
    attributes:
      - key: service.name
        value: alert-manager
        action: upsert

exporters:
  # Debug output
  debug:
    verbosity: detailed
    sampling_initial: 10
    sampling_thereafter: 100
  
  # Prometheus exporter
  prometheus:
    endpoint: 0.0.0.0:8089

extensions:
  # WARNING: DO NOT ADD health_check extension here!
  pprof:
    endpoint: 0.0.0.0:1777
    
  zpages:
    endpoint: 0.0.0.0:55679

service:
  # WARNING: DO NOT ADD health_check to extensions list!
  extensions: [pprof, zpages]
  
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch, attributes, resource]
      exporters: [debug, prometheus]
  
  telemetry:
    logs:
      level: ${env:LOG_LEVEL:-info}
      initial_fields:
        service: alert-manager