receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'anomaly-metrics'
          scrape_interval: 15s
          static_configs:
            - targets: ['${env:ANOMALY_DETECTOR_ENDPOINT}']

processors:
  batch:
    timeout: 5s
    
  attributes:
    actions:
      - key: module
        value: alert-manager
        action: insert

exporters:
  prometheus:
    endpoint: 0.0.0.0:8889
    
  debug:
    verbosity: basic

service:
  pipelines:
    metrics:
      receivers: [prometheus]
      processors: [batch, attributes]
      exporters: [prometheus, debug]
      
  # WARNING: DO NOT ADD health_check to extensions list!
      
  # Health checks are validation-only, not production features.
      
  extensions: []  # NO health_check here!
extensions:
  # WARNING: DO NOT ADD health_check extension here!
  # Health checks have been intentionally removed from production code.
  # Use shared/validation/health-check-all.sh for validation purposes.
  # See shared/validation/README-health-check.md for details.
