# Development Environment Configuration
# Overrides and additions for development deployment

# Include base configurations (conceptual - requires config merging tool)
# include:
#   - ../base/extensions-base.yaml
#   - ../base/receivers-base.yaml
#   - ../base/processors-base.yaml
#   - ../base/exporters-base.yaml

# Development-specific service configuration
service:
  extensions: [health_check, pprof, zpages, memory_ballast]
  pipelines:
    metrics:
      receivers: [postgresql, mysql, sqlquery/postgresql, sqlquery/mysql]
      processors: [memory_limiter, resource, attributes, adaptivesampler, planattributeextractor, batch]
      exporters: [logging, prometheus, debug]
    traces:
      receivers: [otlp]
      processors: [memory_limiter, resource, attributes, planattributeextractor, batch]
      exporters: [logging, debug]
    logs:
      receivers: [otlp]
      processors: [memory_limiter, resource, attributes, batch]
      exporters: [logging]

  telemetry:
    logs:
      level: ${env:OTEL_LOG_LEVEL:-debug}
      encoding: ${env:OTEL_LOG_ENCODING:-json}
      disable_caller: false
      disable_stacktrace: false
    metrics:
      level: ${env:OTEL_METRICS_LEVEL:-detailed}
      address: ${env:OTEL_METRICS_ADDRESS:-0.0.0.0:8888}
    resource:
      service.name: ${env:SERVICE_NAME:-database-intelligence-collector-dev}
      service.version: ${env:SERVICE_VERSION:-2.0.0-dev}
      deployment.environment: development

# Development-specific processor overrides
processors:
  # More lenient memory limits for development
  memory_limiter:
    limit_mib: 256
    spike_limit_mib: 64

  # Higher sampling rates for development debugging
  adaptivesampler:
    sampling_percentage: 100
    max_traces_per_second: 1000

  # Disabled circuit breaker for development
  circuitbreaker:
    max_failures: 50
    failure_threshold_percentage: 90
    timeout: 5s

  # Enhanced debugging for plan extraction
  planattributeextractor:
    enable_anonymization: false  # Disable for easier debugging
    enable_plan_analysis: true
    debug_mode: true

  # Relaxed verification for development
  verification:
    enable_pii_detection: false  # Disable to see actual data
    sample_rate: 1.0

  # No cost control in development
  costcontrol:
    enforcement_enabled: false
    daily_budget_usd: 1000

# Development-specific exporter overrides
exporters:
  # Enhanced logging for development
  logging:
    loglevel: debug
    sampling_initial: 100
    sampling_thereafter: 100

  # Local Prometheus for development
  prometheus:
    endpoint: 0.0.0.0:8889
    namespace: dev_database_intelligence

  # Optional New Relic export (if API key provided)
  otlphttp/newrelic:
    endpoint: ${env:NEW_RELIC_OTLP_ENDPOINT:-https://otlp.nr-data.net}
    headers:
      api-key: ${env:NEW_RELIC_LICENSE_KEY:-}

# Development-specific receiver overrides
receivers:
  # Faster collection intervals for development testing
  postgresql:
    collection_interval: 30s
    
  mysql:
    collection_interval: 30s
    
  sqlquery/postgresql:
    collection_interval: 60s
    
  sqlquery/mysql:
    collection_interval: 60s