# Production Environment Configuration
# Overrides for production deployment

# Production-specific values
receivers:
  postgresql:
    collection_interval: 60s  # Conservative collection
    tls:
      insecure: false
      insecure_skip_verify: false
      ca_file: /etc/ssl/certs/ca-certificates.crt

  mysql:
    collection_interval: 60s
    tls:
      insecure: false
      ca_file: /etc/ssl/certs/ca-certificates.crt

  sqlquery/postgresql:
    collection_interval: 300s  # 5 minutes for custom queries

  sqlquery/mysql:
    collection_interval: 300s

processors:
  memory_limiter:
    check_interval: 5s
    limit_mib: 512  # Conservative memory limit
    spike_limit_mib: 128
    limit_percentage: 80
    spike_limit_percentage: 20

  batch:
    timeout: 10s
    send_batch_size: 2048  # Larger batches for efficiency
    send_batch_max_size: 4096

  # Production filtering
  filter:
    metrics:
      include:
        match_type: regexp
        metric_names:
          - ^db\..*
          - ^system\..*
      exclude:
        match_type: regexp
        metric_names:
          - .*\.test\..*
          - .*\.debug\..*

  # Cost control in production
  costcontrol:
    max_data_points_per_minute: 100000
    max_cardinality: 50000
    enforcement_mode: drop  # Drop excess data
    budgets:
      - service: database-intelligence
        limit: 1000000  # 1M DPM budget
        period: daily

exporters:
  # Disable debug in production
  debug:
    verbosity: basic
    sampling_initial: 2
    sampling_thereafter: 0  # Disable after initial samples

  # Production OTLP settings
  otlphttp:
    compression: gzip
    timeout: 30s
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 300s
      max_elapsed_time: 900s
    sending_queue:
      enabled: true
      num_consumers: 10
      queue_size: 5000
      storage: file_storage

  # Multiple export paths for redundancy
  loadbalancing:
    protocol:
      otlp:
        timeout: 30s
    resolver:
      static:
        hostnames:
          - otlp.nr-data.net:4318
          - otlp-backup.nr-data.net:4318

extensions:
  # Minimal extensions in production
  health_check:
    endpoint: 0.0.0.0:13133
    path: /health
    check_collector_pipeline:
      enabled: true
      interval: 5s
      exporter_failure_threshold: 5

  # File storage for queue persistence
  file_storage:
    directory: /var/lib/otelcol/storage
    timeout: 10s
    compaction:
      on_start: true
      on_shutdown: true

service:
  telemetry:
    logs:
      level: warn  # Minimal logging
      encoding: json
      output_paths: ["stdout"]
      error_output_paths: ["stderr"]
    metrics:
      level: basic
      address: 0.0.0.0:8888

  # Production pipeline configuration
  pipelines:
    metrics:
      processors: [memory_limiter, filter, resource, attributes, batch, costcontrol]
      exporters: [otlphttp, loadbalancing]