version: '3.8'

services:
  resource-monitor:
    # WARNING: DO NOT ADD healthcheck section here!
    # Health checks have been intentionally removed from production Docker configs.
    
    image: otel/opentelemetry-collector-contrib:latest
    container_name: resource-monitor-otel
    environment:
      MODULE_NAME: resource-monitor
      MYSQL_ENDPOINT: ${MYSQL_ENDPOINT:-mysql-test:3306}
      MYSQL_USER: ${MYSQL_USER:-root}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-test}
      EXPORT_PORT: 8088
      OTEL_SERVICE_NAME: resource-monitor
      # New Relic Configuration
      NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY}
      NEW_RELIC_OTLP_ENDPOINT: ${NEW_RELIC_OTLP_ENDPOINT}
      NEW_RELIC_ACCOUNT_ID: ${NEW_RELIC_ACCOUNT_ID}
      NEW_RELIC_API_KEY: ${NEW_RELIC_API_KEY}
      ENVIRONMENT: production
      CLUSTER_NAME: database-intelligence-cluster
      # Host metrics configuration
      HOST_PROC: /host/proc
      HOST_SYS: /host/sys
      HOST_ETC: /host/etc
      HOST_VAR: /host/var
      HOST_RUN: /host/run
      HOST_DEV: /host/dev
    ports:
      - "8088:8088"     # Module export port
      - "8904:8889"     # Internal metrics
      - "4331:4317"     # OTLP gRPC receiver
      - "4332:4318"     # OTLP HTTP receiver
      - "55686:55679"   # ZPages
      - "1782:1777"     # pprof
      # WARNING: DO NOT expose port 13133 (health check port)!
    volumes:
      - ./config:/etc/otel:ro
      - ./logs:/tmp/logs
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/hostname:/etc/hostname:ro
    privileged: true
    pid: host
    command: ["--config", "/etc/otel/${COLLECTOR_CONFIG:-collector-simple.yaml}"]
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '2.0'
        reservations:
          memory: 512M
          cpus: '0.5'