version: '3.8'

services:
  alert-manager:
    # WARNING: DO NOT ADD healthcheck section here!
    # Health checks have been intentionally removed from production Docker configs.
    # Use shared/validation/health-check-all.sh for validation purposes.
    # See shared/validation/README-health-check.md for details.
    
    build: .
    env_file:
      - ../../shared/config/service-endpoints.env
    environment:
      MODULE_NAME: alert-manager
      EXPORT_PORT: 8089
      OTEL_SERVICE_NAME: alert-manager
      # Alert-specific configuration
      WEBHOOK_ENDPOINT: ${WEBHOOK_ENDPOINT:-http://localhost:9999/alerts}
      ALERT_FILE_PATH: ${ALERT_FILE_PATH:-/tmp/alerts.log}
      # Override specific endpoints if needed
      COLLECTOR_CONFIG: ${COLLECTOR_CONFIG:-collector.yaml}
    ports:
      - "8089:8089"      # Module metrics
      - "8897:8889"      # OTLP gRPC debug
      - "4329:4318"      # OTLP HTTP receiver (unique port)
      # WARNING: DO NOT expose port 13133 (health check port)!
      # Health check ports have been intentionally removed.
    volumes:
      - ./config:/etc/otel
      - ../../shared/config:/etc/shared
      - /tmp:/tmp  # For alert file logging
    command: ["--config", "/etc/otel/${COLLECTOR_CONFIG:-collector.yaml}"]