{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "database-intelligence.fullname" . }}
  namespace: {{ include "database-intelligence.namespace" . }}
  labels:
    {{- include "database-intelligence.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "database-intelligence.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  {{- if .Values.networkPolicy.allowExternal }}
  ingress:
    - ports:
        - port: {{ .Values.service.ports.metrics }}
        - port: {{ .Values.service.ports.prometheus }}
        - port: {{ .Values.service.ports.health }}
    {{- if .Values.networkPolicy.additionalIngress }}
    {{- toYaml .Values.networkPolicy.additionalIngress | nindent 4 }}
    {{- end }}
  {{- else }}
  ingress:
    # Allow Prometheus scraping from monitoring namespace
    - from:
        - namespaceSelector:
            matchLabels:
              name: monitoring
        - podSelector:
            matchLabels:
              app: prometheus
      ports:
        - protocol: TCP
          port: {{ .Values.service.ports.metrics }}
        - protocol: TCP
          port: {{ .Values.service.ports.prometheus }}
    # Allow health checks
    - ports:
        - protocol: TCP
          port: {{ .Values.service.ports.health }}
    {{- if .Values.networkPolicy.additionalIngress }}
    {{- toYaml .Values.networkPolicy.additionalIngress | nindent 4 }}
    {{- end }}
  {{- end }}
  egress:
    # Allow DNS resolution
    - to:
        - namespaceSelector:
            matchLabels:
              name: kube-system
        - podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    {{- if .Values.config.postgres.enabled }}
    # Allow PostgreSQL connections
    - to:
        - podSelector: {}
      ports:
        - protocol: TCP
          port: {{ .Values.config.postgres.port }}
    {{- end }}
    {{- if .Values.config.mysql.enabled }}
    # Allow MySQL connections
    - to:
        - podSelector: {}
      ports:
        - protocol: TCP
          port: {{ .Values.config.mysql.port }}
    {{- end }}
    # Allow OTLP export to New Relic
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              - 10.0.0.0/8
              - 172.16.0.0/12
              - 192.168.0.0/16
      ports:
        - protocol: TCP
          port: 4317
        - protocol: TCP
          port: 443
    {{- if .Values.networkPolicy.additionalEgress }}
    {{- toYaml .Values.networkPolicy.additionalEgress | nindent 4 }}
    {{- end }}
{{- end }}