{{- if and .Values.serviceAccount.create .Values.rbac.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "database-intelligence.fullname" . }}
  namespace: {{ include "database-intelligence.namespace" . }}
  labels:
    {{- include "database-intelligence.labels" . | nindent 4 }}
rules:
  {{- if .Values.rbac.rules }}
  {{- toYaml .Values.rbac.rules | nindent 2 }}
  {{- else }}
  # Default rules for database intelligence collector
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list"]
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "database-intelligence.fullname" . }}
  namespace: {{ include "database-intelligence.namespace" . }}
  labels:
    {{- include "database-intelligence.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "database-intelligence.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "database-intelligence.serviceAccountName" . }}
    namespace: {{ include "database-intelligence.namespace" . }}
{{- end }}