{{- if include "database-intelligence.createSecret" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "database-intelligence.secretName" . }}
  namespace: {{ include "database-intelligence.namespace" . }}
  labels:
    {{- include "database-intelligence.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.config.postgres.enabled }}
  postgres-username: {{ .Values.config.postgres.username | b64enc | quote }}
  postgres-password: {{ .Values.config.postgres.password | b64enc | quote }}
  {{- end }}
  {{- if .Values.config.mysql.enabled }}
  mysql-username: {{ .Values.config.mysql.username | b64enc | quote }}
  mysql-password: {{ .Values.config.mysql.password | b64enc | quote }}
  {{- end }}
  new-relic-license-key: {{ required "New Relic license key is required" .Values.config.newrelic.licenseKey | b64enc | quote }}
{{- end }}