# Development Environment Values
# This file overrides the default values.yaml for development environments

# Enable debug logging
config:
  mode: experimental  # Use experimental features in dev
  service:
    telemetry:
      logs:
        level: debug
  
  # Enable all receivers for testing
  receivers:
    postgresql:
      enabled: true
      collection_interval: 30s
    mysql:
      enabled: true
      collection_interval: 30s
    sqlquery:
      enabled: true
      queries:
        - name: active_sessions_dev
          query: "SELECT * FROM pg_stat_activity WHERE state = 'active'"
          collection_interval: 10s

  # Enable all experimental processors
  processors:
    experimental:
      adaptiveSampler:
        enabled: true
        default_sampling_rate: 1.0  # Sample everything in dev
      circuitBreaker:
        enabled: true
        failure_threshold: 10  # Higher threshold for dev
      planExtractor:
        enabled: true
      verification:
        enabled: true
        pii_detection:
          enabled: false  # Disable PII detection in dev

  # Use debug exporter alongside others
  exporters:
    debug:
      enabled: true
      verbosity: detailed

# Single replica for development
replicaCount: 1

# Minimal resources for local development
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Disable autoscaling in dev
autoscaling:
  enabled: false

# Enable persistence for testing state management
persistence:
  enabled: true
  size: 1Gi
  storageClass: standard

# Simplified service for local access
service:
  type: ClusterIP

# Disable network policies in dev
networkPolicy:
  enabled: false

# Enable all monitoring features
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    interval: 30s

# Development-specific environment variables
env:
  - name: ENVIRONMENT
    value: development
  - name: LOG_LEVEL
    value: debug
  - name: ENABLE_PROFILING
    value: "true"

# Mount local configs for easy testing
extraVolumeMounts:
  - name: dev-configs
    mountPath: /etc/otel/dev-configs
    readOnly: true

extraVolumes:
  - name: dev-configs
    configMap:
      name: dev-test-configs

# Enable debug endpoints
extraPorts:
  - name: pprof
    containerPort: 6060
    protocol: TCP
  - name: zpages
    containerPort: 55679
    protocol: TCP