receivers:
  mysql:
    endpoint: ${env:MYSQL_ENDPOINT}
    username: ${env:MYSQL_USER}
    password: ${env:MYSQL_PASSWORD}
    collection_interval: 10s
    transport: tcp
    metrics:
      mysql.uptime:
        enabled: true
      mysql.connections:
        enabled: true
      mysql.threads:
        enabled: true
      mysql.operations:
        enabled: true
      mysql.handlers:
        enabled: true
      mysql.double_writes:
        enabled: true
      mysql.log_operations:
        enabled: true
      mysql.page_operations:
        enabled: true
      mysql.row_locks:
        enabled: true
      mysql.row_operations:
        enabled: true
      mysql.locks:
        enabled: true
      mysql.sorts:
        enabled: true
      mysql.table_open_cache:
        enabled: true

processors:
  batch:
    timeout: 5s
    send_batch_size: 1000
  
  attributes:
    actions:
      - key: module
        value: core-metrics
        action: insert
      - key: mysql.endpoint
        value: ${env:MYSQL_ENDPOINT}
        action: insert

  resource:
    attributes:
      - key: service.name
        value: ${env:OTEL_SERVICE_NAME}
        action: upsert

exporters:
  prometheus:
    endpoint: "0.0.0.0:${env:EXPORT_PORT}"
    namespace: mysql
    const_labels:
      module: core-metrics
  
  logging:
    loglevel: info

service:
  pipelines:
    metrics:
      receivers: [mysql]
      processors: [batch, attributes, resource]
      exporters: [prometheus, logging]
  
  extensions: [health_check]

extensions:
  health_check:
    endpoint: 0.0.0.0:13133