receivers:
  mysql:
    endpoint: ${env:MYSQL_ENDPOINT}
    username: ${env:MYSQL_USER}
    password: ${env:MYSQL_PASSWORD}
    collection_interval: 10s
    transport: tcp

processors:
  # Memory management
  memory_limiter:
    check_interval: 5s
    limit_percentage: 80
    spike_limit_percentage: 30

  batch:
    timeout: 5s
    send_batch_size: 1000
  
  attributes:
    actions:
      - key: module
        value: core-metrics
        action: insert
      - key: mysql.endpoint
        value: ${env:MYSQL_ENDPOINT}
        action: insert

  resource:
    attributes:
      - key: service.name
        value: ${env:OTEL_SERVICE_NAME}
        action: upsert

exporters:
  # Prometheus exporter for metrics
  prometheus:
    endpoint: 0.0.0.0:8889
    
  debug:
    verbosity: detailed

service:
  pipelines:
    metrics:
      receivers: [mysql]
      processors: [memory_limiter, batch, attributes, resource]
      exporters: [prometheus, debug]
  
  extensions: [health_check]

extensions:
  health_check:
    endpoint: 0.0.0.0:13133