# Resource Monitor - Simple Configuration
# Basic system resource monitoring

receivers:
  # Host metrics receiver
  hostmetrics:
    collection_interval: 10s
    scrapers:
      cpu:
        metrics:
          system.cpu.utilization:
            enabled: true
      
      memory:
        metrics:
          system.memory.usage:
            enabled: true
          system.memory.utilization:
            enabled: true
      
      disk:
        metrics:
          system.disk.io:
            enabled: true
          system.disk.operations:
            enabled: true
      
      filesystem:
        metrics:
          system.filesystem.usage:
            enabled: true
          system.filesystem.utilization:
            enabled: true
      
      network:
        metrics:
          system.network.io:
            enabled: true
          system.network.packets:
            enabled: true
      
      load:
        metrics:
          system.cpu.load_average.1m:
            enabled: true
          system.cpu.load_average.5m:
            enabled: true
          system.cpu.load_average.15m:
            enabled: true
      
      processes:

processors:
  # Memory management
  memory_limiter:
    check_interval: 5s
    limit_percentage: 80
    spike_limit_percentage: 30
  
  batch:
    timeout: 10s
    send_batch_size: 1000
  
  # Add module attributes
  attributes:
    actions:
      - key: module
        value: resource-monitor
        action: insert
      - key: environment
        value: ${env:ENVIRONMENT:-production}
        action: insert
  
  # Resource processor
  resource:
    attributes:
      - key: service.name
        value: resource-monitor
        action: upsert

exporters:
  # Debug output
  debug:
    verbosity: detailed
    sampling_initial: 10
    sampling_thereafter: 100
  
  # Prometheus exporter
  prometheus:
    endpoint: 0.0.0.0:8088

extensions:
  # WARNING: DO NOT ADD health_check extension here!
  pprof:
    endpoint: 0.0.0.0:1777
    
  zpages:
    endpoint: 0.0.0.0:55679

service:
  # WARNING: DO NOT ADD health_check to extensions list!
  extensions: [pprof, zpages]
  
  pipelines:
    metrics:
      receivers: [hostmetrics]
      processors: [memory_limiter, batch, attributes, resource]
      exporters: [debug, prometheus]
  
  telemetry:
    logs:
      level: ${env:LOG_LEVEL:-info}
      initial_fields:
        service: resource-monitor