# Minimal OTEL Collector Configuration
# This is the simplest possible configuration for getting started

receivers:
  # PostgreSQL infrastructure metrics
  postgresql:
    endpoint: ${env:POSTGRES_HOST:-localhost}:${env:POSTGRES_PORT:-5432}
    username: ${env:POSTGRES_USER:-postgres}
    password: ${env:POSTGRES_PASSWORD:-postgres}
    databases:
      - ${env:POSTGRES_DATABASE:-postgres}
    collection_interval: 60s

processors:
  # Prevent OOM
  memory_limiter:
    check_interval: 1s
    limit_percentage: 80
    
  # Batch for efficiency
  batch:
    timeout: 10s

exporters:
  # Debug output (console)
  debug:
    verbosity: detailed
    
  # Prometheus metrics (optional)
  prometheus:
    endpoint: 0.0.0.0:8888

service:
  pipelines:
    metrics:
      receivers: [postgresql]
      processors: [memory_limiter, batch]
      exporters: [debug, prometheus]
      
  telemetry:
    logs:
      level: info