receivers:
  postgresql:
    endpoint: localhost:5432
    username: postgres
    password: postgres
    databases:
      - postgres
    collection_interval: 10s
    tls:
      insecure: true
      
  mysql:
    endpoint: localhost:3306
    username: root
    password: mysql
    collection_interval: 10s
    tls:
      insecure: true

processors:
  memory_limiter:
    check_interval: 1s
    limit_percentage: 75
    spike_limit_percentage: 20
    
  batch:
    send_batch_size: 100
    timeout: 5s
    
  resource:
    attributes:
      - key: service.name
        value: database-intelligence
        action: upsert
      - key: environment
        value: demo
        action: upsert

exporters:
  debug:
    verbosity: detailed
    sampling_initial: 5
    sampling_thereafter: 20
    
  prometheus:
    endpoint: 0.0.0.0:9090
    namespace: db_intelligence
    
  file:
    path: ./metrics.json

extensions:
  health_check:
    endpoint: 0.0.0.0:13133
    path: "/health"
    
  zpages:
    endpoint: 0.0.0.0:55679

service:
  extensions: [health_check, zpages]
  
  telemetry:
    logs:
      level: info
      encoding: json
      output_paths: ["stdout"]
    metrics:
      level: detailed
      address: 0.0.0.0:8888
      
  pipelines:
    metrics:
      receivers: [postgresql, mysql]
      processors: [memory_limiter, resource, batch]
      exporters: [debug, prometheus, file]