receivers:
  postgresql:
    endpoint: localhost:5432
    username: postgres
    password: postgres
    databases:
      - postgres
    collection_interval: 10s
    tls:
      insecure: true
      
  mysql:
    endpoint: localhost:3306
    username: root
    password: mysql
    collection_interval: 10s
    tls:
      insecure: true

processors:
  memory_limiter:
    check_interval: 1s
    limit_percentage: 75
    spike_limit_percentage: 20
    
  batch:
    send_batch_size: 100
    timeout: 5s

exporters:
  debug:
    verbosity: detailed
    
  file:
    path: ./metrics.json

service:
  telemetry:
    logs:
      level: info
      
  pipelines:
    metrics:
      receivers: [postgresql, mysql]
      processors: [memory_limiter, batch]
      exporters: [debug, file]