dist:
  name: database-intelligence
  description: Database Intelligence Collector with custom processors
  version: 2.0.0
  output_path: ./build-official
  otelcol_version: 0.105.0

extensions:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckextension v0.105.0

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.105.0
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.105.0
  - gomod: go.opentelemetry.io/collector/exporter/otlphttpexporter v0.105.0

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.105.0
  - gomod: go.opentelemetry.io/collector/processor/memorylimiterprocessor v0.105.0

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.105.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/mysqlreceiver v0.105.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/postgresqlreceiver v0.105.0
