dist:
  name: database-intelligence-collector
  description: Database Intelligence Collector with custom processors
  version: 2.0.0
  output_path: ./build
  otelcol_version: 0.102.1

extensions:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckextension v0.102.1
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/pprofextension v0.102.1

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.102.1
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.102.1
  - gomod: go.opentelemetry.io/collector/exporter/otlphttpexporter v0.102.1

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.102.1
  - gomod: go.opentelemetry.io/collector/processor/memorylimiterprocessor v0.102.1
  # Custom processors
  - path: ./processors/adaptivesampler
  - path: ./processors/circuitbreaker
  - path: ./processors/costcontrol
  - path: ./processors/nrerrormonitor
  - path: ./processors/planattributeextractor
  - path: ./processors/querycorrelator
  - path: ./processors/verification

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.102.1
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/mysqlreceiver v0.102.1
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/postgresqlreceiver v0.102.1