dist:
  name: database-intelligence-collector
  description: Database Intelligence Collector with custom processors
  version: 2.0.0
  output_path: ./build
  otelcol_version: 0.109.0

extensions:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckextension v0.109.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/pprofextension v0.109.0

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.109.0
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.109.0
  - gomod: go.opentelemetry.io/collector/exporter/otlphttpexporter v0.109.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/fileexporter v0.109.0

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.109.0
  - gomod: go.opentelemetry.io/collector/processor/memorylimiterprocessor v0.109.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/attributesprocessor v0.109.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/filterprocessor v0.109.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourceprocessor v0.109.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/transformprocessor v0.109.0
  # Custom processors
  - gomod: github.com/database-intelligence/processors/adaptivesampler v0.0.0
    path: ./processors/adaptivesampler
  - gomod: github.com/database-intelligence/processors/circuitbreaker v0.0.0
    path: ./processors/circuitbreaker
  - gomod: github.com/database-intelligence/processors/costcontrol v0.0.0
    path: ./processors/costcontrol
  - gomod: github.com/database-intelligence/processors/nrerrormonitor v0.0.0
    path: ./processors/nrerrormonitor
  - gomod: github.com/database-intelligence/processors/planattributeextractor v0.0.0
    path: ./processors/planattributeextractor
  - gomod: github.com/database-intelligence/processors/querycorrelator v0.0.0
    path: ./processors/querycorrelator
  - gomod: github.com/database-intelligence/processors/verification v0.0.0
    path: ./processors/verification

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.109.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/mysqlreceiver v0.109.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/postgresqlreceiver v0.109.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/sqlqueryreceiver v0.109.0