receivers:
  otlp:
    protocols:
      grpc:
        endpoint: localhost:4317

  # Test custom receivers when available
  # ash:
  #   driver: postgres
  #   datasource: host=localhost port=5432 user=postgres password=postgres dbname=testdb sslmode=disable
  #   collection_interval: 10s
  
  # enhancedsql:
  #   driver: postgres
  #   datasource: host=localhost port=5432 user=postgres password=postgres dbname=testdb sslmode=disable
  #   queries:
  #     - metric_name: custom_metric
  #       query: "SELECT count(*) as value FROM test_table"

processors:
  batch:
    timeout: 10s

exporters:
  debug:
    verbosity: detailed

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]
