extensions:
  zpages:
    endpoint: 0.0.0.0:55679

receivers:
  # PostgreSQL receiver for database metrics
  postgresql:
    endpoint: localhost:5432
    username: postgres
    password: postgres
    databases:
      - postgres
    tls:
      insecure: true
    collection_interval: 30s

  mysql:
    endpoint: localhost:3306
    username: root
    password: mysql
    database: mysql
    collection_interval: 30s

processors:
  memory_limiter:
    check_interval: 1s
    limit_mib: 512

  resource:
    attributes:
      - key: collector.name
        value: otelcol
        action: upsert

  batch:
    timeout: 10s

exporters:
  debug:
    verbosity: detailed
    sampling_initial: 5
    sampling_thereafter: 10

service:
  extensions: [zpages]
  pipelines:
    metrics:
      receivers: [postgresql, mysql]
      processors: [memory_limiter, resource, batch]
      exporters: [debug]
      
  telemetry:
    logs:
      level: info
    metrics:
      level: detailed
      address: 0.0.0.0:8888