receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  resource:
    attributes:
      - key: collector.name
        value: otelcol
        action: upsert
  batch:

exporters:
  debug:
    verbosity: detailed

service:
  telemetry:
    logs:
      level: debug
  pipelines:
    traces:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [debug]
    metrics:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [debug]