# Base Configuration Template
# This file includes all base component configurations
# Use with environment-specific overlays

# Include all component configurations
# These files define available components but don't create pipelines
# Actual component selection happens in mode files (config-only.yaml, enhanced.yaml)

# Load receiver definitions
${file:base/receivers.yaml}

# Load processor definitions  
${file:base/processors.yaml}

# Load exporter definitions
${file:base/exporters.yaml}

# Load extension definitions
${file:base/extensions.yaml}

# Service configuration is defined in mode files
# This allows different modes to use different pipelines