# Basic collector configuration for getting started
# This provides a minimal setup with OTLP receivers and New Relic export

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 10s
    send_batch_size: 1000
  
  memory_limiter:
    check_interval: 5s
    limit_mib: 512

exporters:
  debug:
    verbosity: detailed
    sampling_initial: 2
    sampling_thereafter: 500
  
  otlp/newrelic:
    endpoint: "${NEW_RELIC_OTLP_ENDPOINT:-otlp.nr-data.net:4317}"
    headers:
      api-key: "${NEW_RELIC_LICENSE_KEY}"
    compression: gzip

service:
  telemetry:
    logs:
      level: info
  
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [debug, otlp/newrelic]
    
    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [debug, otlp/newrelic]
    
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [debug, otlp/newrelic]