version: '3.8'

services:
  mysql-test:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: testdb
    ports:
      - "3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./src/init.sql:/docker-entrypoint-initdb.d/init.sql
    
  wait-profiler:
    build: .
    environment:
      MODULE_NAME: wait-profiler
      MYSQL_ENDPOINT: mysql-test:3306
      MYSQL_USER: root
      MYSQL_PASSWORD: test
      EXPORT_PORT: 8083
      OTEL_SERVICE_NAME: wait-profiler
    ports:
      - "8083:8083"
      - "8891:8889"
    depends_on:
      mysql-test:
        condition: service_healthy
    volumes:
      - ./config:/etc/otel
    command: ["--config", "/etc/otel/${COLLECTOR_CONFIG:-collector.yaml}"]