# Database Intelligence - High Availability Configuration
# This configuration includes replicas and load balancing

version: '3.8'

services:
  # PostgreSQL Primary
  postgres-primary:
    image: postgres:16
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_REPLICATION_MODE: master
      POSTGRES_REPLICATION_USER: replicator
      POSTGRES_REPLICATION_PASSWORD: replicator_password
    volumes:
      - postgres_primary_data:/var/lib/postgresql/data
    networks:
      - database-intelligence

  # PostgreSQL Replica
  postgres-replica:
    image: postgres:16
    environment:
      POSTGRES_REPLICATION_MODE: slave
      POSTGRES_MASTER_HOST: postgres-primary
      POSTGRES_MASTER_PORT_NUMBER: 5432
      POSTGRES_REPLICATION_USER: replicator
      POSTGRES_REPLICATION_PASSWORD: replicator_password
    depends_on:
      - postgres-primary
    networks:
      - database-intelligence

  # Multiple collector instances
  collector-1:
    extends:
      file: docker-compose.yaml
      service: collector
    container_name: database-intelligence-collector-1
    networks:
      - database-intelligence

  collector-2:
    extends:
      file: docker-compose.yaml
      service: collector
    container_name: database-intelligence-collector-2
    networks:
      - database-intelligence

  # Load balancer
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx-ha.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - collector-1
      - collector-2
    networks:
      - database-intelligence

volumes:
  postgres_primary_data:
  postgres_replica_data:

networks:
  database-intelligence:
    driver: bridge
