receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  
  postgresql:
    endpoint: ${DB_POSTGRES_HOST:localhost}:${DB_POSTGRES_PORT:5432}
    username: ${DB_POSTGRES_USER:postgres}
    password: ${DB_POSTGRES_PASSWORD:postgres}
    databases:
      - ${DB_POSTGRES_DATABASE:postgres}
    collection_interval: 10s
  
  mysql:
    endpoint: ${DB_MYSQL_HOST:localhost}:${DB_MYSQL_PORT:3306}
    username: ${DB_MYSQL_USER:root}
    password: ${DB_MYSQL_PASSWORD:mysql}
    database: ${DB_MYSQL_DATABASE:mysql}
    collection_interval: 10s

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
  
  memory_limiter:
    check_interval: 1s
    limit_mib: ${MEMORY_LIMIT_MIB:512}
  
  resource:
    attributes:
      - key: service.name
        value: ${SERVICE_NAME:database-intelligence-collector}
        action: upsert
      - key: service.version
        value: ${SERVICE_VERSION:2.0.0}
        action: upsert
      - key: deployment.environment
        value: ${DEPLOYMENT_ENVIRONMENT:production}
        action: upsert

exporters:
  otlphttp:
    endpoint: ${OTLP_ENDPOINT:https://otlp.nr-data.net}
    headers:
      api-key: ${NEW_RELIC_LICENSE_KEY}
    compression: gzip
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s
  
  debug:
    verbosity: ${DEBUG_VERBOSITY:normal}

extensions:
  health_check:
    endpoint: 0.0.0.0:13133

service:
  extensions: [health_check]
  pipelines:
    metrics/postgresql:
      receivers: [postgresql]
      processors: [memory_limiter, resource, batch]
      exporters: [otlphttp]
    metrics/mysql:
      receivers: [mysql]
      processors: [memory_limiter, resource, batch]
      exporters: [otlphttp]
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, resource, batch]
      exporters: [otlphttp]
    traces:
      receivers: [otlp]
      processors: [memory_limiter, resource, batch]
      exporters: [otlphttp]
    logs:
      receivers: [otlp]
      processors: [memory_limiter, resource, batch]
      exporters: [otlphttp]