apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgres-collector.fullname" . }}-config
  labels:
    {{- include "postgres-collector.labels" . | nindent 4 }}
data:
  collector.yaml: |
    {{- .Values.collectorConfig | nindent 4 }}