# Single Instance Database Intelligence Setup
# Simplified deployment without Redis dependency

services:
  # Single collector instance
  collector:
    image: database-intelligence/collector:latest
    container_name: db-intel-collector
    hostname: db-intel-collector
    depends_on:
      postgres-primary:
        condition: service_healthy
    volumes:
      - ../../config/collector-resilient.yaml:/etc/otel-collector-config.yaml
      - /var/log/collector:/var/log
      - collector-state:/var/lib/otel  # Local state storage
    environment:
      - NEW_RELIC_LICENSE_KEY=${NEW_RELIC_LICENSE_KEY}
      - NEW_RELIC_ACCOUNT_ID=${NEW_RELIC_ACCOUNT_ID}
      - PG_HOST=postgres-primary
      - PG_PORT=5432
      - PG_USER=newrelic_monitor
      - PG_PASSWORD=monitor123
      - PG_DATABASE=testdb
      - PG_REPLICA_DSN=postgres://newrelic_monitor:monitor123@postgres-primary:5432/testdb?sslmode=disable
      - DEPLOYMENT_ENV=production
      - LOG_LEVEL=info
    ports:
      - "8888:8888"   # Metrics
      - "13133:13133" # Health check
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
    networks:
      - db-intelligence
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'

  # PostgreSQL for testing
  postgres-primary:
    image: postgres:15-alpine
    container_name: db-intel-postgres
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ../docker/init-scripts/postgres-init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
    ports:
      - "5432:5432"
    networks:
      - db-intelligence
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  collector-state:  # Local storage for processor state
  postgres-data:

networks:
  db-intelligence:
    driver: bridge