# Minimal test configuration for E2E validation
# Uses only core components to test basic connectivity

receivers:
  # Simple receiver for testing
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  # Only use the custom processors that are working
  planattributeextractor:
    safe_mode: true
    timeout: 100ms
    error_mode: ignore
    query_anonymization:
      enabled: true

exporters:
  # Debug output for testing
  debug:
    verbosity: detailed
    sampling_initial: 10
    sampling_thereafter: 100

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [planattributeextractor]
      exporters: [debug]
  
  telemetry:
    logs:
      level: info
    metrics:
      level: detailed
      address: 0.0.0.0:8888