version: '3.8'

services:
  anomaly-detector:
    build: .
    environment:
      MODULE_NAME: anomaly-detector
      EXPORT_PORT: 8084
      OTEL_SERVICE_NAME: anomaly-detector
      # Prometheus federation endpoints for pulling metrics from other modules
      CORE_METRICS_ENDPOINT: http://host.docker.internal:8081/metrics
      SQL_INTELLIGENCE_ENDPOINT: http://host.docker.internal:8082/metrics
      WAIT_PROFILER_ENDPOINT: http://host.docker.internal:8083/metrics
      # Anomaly detection thresholds
      CONNECTION_SPIKE_THRESHOLD: "2.0"  # 2x standard deviation
      LATENCY_DEVIATION_THRESHOLD: "3.0"  # 3x standard deviation
      WAIT_EVENT_THRESHOLD: "2.5"  # 2.5x standard deviation
      RESOURCE_USAGE_THRESHOLD: "2.0"  # 2x standard deviation
    ports:
      - "8084:8084"
      - "8892:8889"
    volumes:
      - ./config:/etc/otel
    command: ["--config", "/etc/otel/${COLLECTOR_CONFIG:-collector.yaml}"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:13133/"]
      interval: 30s
      timeout: 3s
      start-period: 10s
      retries: 3