receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    send_batch_size: 1000
    timeout: 10s
  
  memory_limiter:
    check_interval: 5s
    limit_mib: 512

exporters:
  debug:
    verbosity: normal
    sampling_initial: 2
    sampling_thereafter: 500

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [debug]
  
  telemetry:
    logs:
      level: info