apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: database-intelligence

namePrefix: dbintel-

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: database-intelligence

commonAnnotations:
  app.kubernetes.io/version: "1.0.0"

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - rbac.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - networkpolicy.yaml

configMapGenerator:
  - name: database-intelligence-config
    behavior: merge
    files:
      - collector-config.yaml=../../configs/collector-config.yaml

secretGenerator:
  - name: database-intelligence-secret
    behavior: merge
    envs:
      - secrets.env

replicas:
  - name: database-intelligence-collector
    count: 1

images:
  - name: database-intelligence-collector
    newName: database-intelligence-collector
    newTag: latest

patches:
  - target:
      kind: Deployment
      name: database-intelligence-collector
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: KUSTOMIZE_APPLIED
          value: "true"

vars:
  - name: COLLECTOR_IMAGE
    objref:
      kind: Deployment
      name: database-intelligence-collector
      apiVersion: apps/v1
    fieldref:
      fieldpath: spec.template.spec.containers[0].image

configurations:
  - kustomizeconfig.yaml