apiVersion: v1
kind: Secret
metadata:
  name: database-intelligence-secret
  namespace: database-intelligence
  labels:
    app.kubernetes.io/name: database-intelligence
    app.kubernetes.io/component: secrets
type: Opaque
stringData:
  # PostgreSQL connection credentials
  POSTGRES_HOST: "postgresql.database.svc.cluster.local"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "monitoring"
  POSTGRES_PASSWORD: "changeme"
  POSTGRES_DB: "postgres"
  
  # New Relic credentials
  NEW_RELIC_LICENSE_KEY: "YOUR_NEW_RELIC_LICENSE_KEY"
  OTLP_ENDPOINT: "otlp.nr-data.net:4317"
  
  # Environment configuration
  ENVIRONMENT: "production"
  LOG_LEVEL: "info"
  VERSION: "1.0.0"