mysql_monitoring:
  endpoints:
    - name: "mysql-primary"
      endpoint: "mysql-primary.default.svc.cluster.local:3306"
      username: "${MYSQL_MONITOR_USER}"
      password: "${MYSQL_MONITOR_PASSWORD}"
      database: ""
      role: "primary"
      
    - name: "mysql-replica-1"
      endpoint: "mysql-replica-1.default.svc.cluster.local:3306"
      username: "${MYSQL_MONITOR_USER}"
      password: "${MYSQL_MONITOR_PASSWORD}"
      database: ""
      role: "replica"
  
  collection:
    interval: 10s
    timeout: 5s
    initial_delay: 10s
    
  features:
    collect_table_metrics: true
    collect_index_metrics: true
    collect_query_digest: true
    collect_replica_metrics: true
    collect_lock_metrics: true
    performance_schema_enabled: true
    
  limits:
    max_tables: 100
    max_indexes: 200
    max_query_digests: 50
    max_schemas: 10
    
  slow_query:
    threshold_ms: 1000
    emit_traces: true
    emit_logs: true
    
  filters:
    exclude_schemas:
      - "mysql"
      - "information_schema"
      - "performance_schema"
      - "sys"
    include_schemas: []
    
  new_relic:
    account_id: "${NEW_RELIC_ACCOUNT_ID}"
    api_key: "${NEW_RELIC_API_KEY}"
    region: "US"
    
    custom_attributes:
      environment: "${ENVIRONMENT}"
      team: "${TEAM_NAME}"
      service: "${SERVICE_NAME}"
      cost_center: "${COST_CENTER}"

performance:
  queries:
    use_prepared_statements: true
    query_timeout: 5s
    batch_queries:
      enabled: true
      batch_size: 100
      
  connection_pool:
    min_connections: 1
    max_connections: 5
    connection_lifetime: 300s
    idle_timeout: 60s
    
  cache:
    metadata_cache:
      enabled: true
      ttl: 300s
    schema_cache:
      enabled: true
      ttl: 600s
      
  sampling:
    table_metrics:
      enabled: true
      threshold: 1000
      sample_rate: 0.1
    index_metrics:
      enabled: true
      threshold: 2000
      sample_rate: 0.05
      
  circuit_breaker:
    enabled: true
    failure_threshold: 5
    recovery_timeout: 30s
    
  rate_limit:
    enabled: true
    queries_per_second: 100
    burst: 200

security:
  tls:
    enabled: true
    ca_cert: /etc/mysql-certs/ca.crt
    client_cert: /etc/mysql-certs/client.crt
    client_key: /etc/mysql-certs/client.key
    verify_mode: VERIFY_IDENTITY
    
  credential_rotation:
    enabled: true
    rotation_period: 30d
    grace_period: 7d
    
  network_policies:
    enabled: true
    ingress:
      - from:
        - namespaceSelector:
            matchLabels:
              name: monitoring
    egress:
      - to:
        - namespaceSelector:
            matchLabels:
              name: default
        ports:
        - protocol: TCP
          port: 3306
      - to:
        - namespaceSelector:
            matchLabels:
              name: kube-system
        ports:
        - protocol: TCP
          port: 53
          
  rbac:
    create: true
    rules:
      - apiGroups: [""]
        resources: ["secrets"]
        verbs: ["get"]
      - apiGroups: [""]
        resources: ["configmaps"]
        verbs: ["get", "list", "watch"]