receivers:
  mysql/primary:
    endpoint: ${env:MYSQL_PRIMARY_ENDPOINT}
    username: ${env:MYSQL_USER}
    password: ${env:MYSQL_PASSWORD}
    database: ${env:MYSQL_DATABASE}
    collection_interval: 10s
    initial_delay: 1s
    metrics:
      mysql.buffer_pool.data_pages:
        enabled: true
      mysql.buffer_pool.limit:
        enabled: true
      mysql.buffer_pool.operations:
        enabled: true
      mysql.buffer_pool.page_flushes:
        enabled: true
      mysql.buffer_pool.pages:
        enabled: true
      mysql.buffer_pool.usage:
        enabled: true
      mysql.client.network.io:
        enabled: true
      mysql.commands:
        enabled: true
      mysql.connection.count:
        enabled: true
      mysql.connection.errors:
        enabled: true
      mysql.double_writes:
        enabled: true
      mysql.handlers:
        enabled: true
      mysql.index.io.wait.count:
        enabled: true
      mysql.index.io.wait.time:
        enabled: true
      mysql.innodb.buffer_pool_pages:
        enabled: true
      mysql.innodb.data_fsyncs:
        enabled: true
      mysql.innodb.os_log_pending_fsyncs:
        enabled: true
      mysql.innodb.pages_created:
        enabled: true
      mysql.innodb.pages_read:
        enabled: true
      mysql.innodb.pages_written:
        enabled: true
      mysql.innodb.row_lock_time:
        enabled: true
      mysql.innodb.row_lock_waits:
        enabled: true
      mysql.innodb.row_operations:
        enabled: true
      mysql.joins:
        enabled: true
      mysql.locks:
        enabled: true
      mysql.log_operations:
        enabled: true
      mysql.opened_resources:
        enabled: true
      mysql.page_operations:
        enabled: true
      mysql.prepared_statements:
        enabled: true
      mysql.query.client.count:
        enabled: true
      mysql.query.count:
        enabled: true
      mysql.query.slow.count:
        enabled: true
      mysql.replica.sql_delay:
        enabled: true
      mysql.replica.time_behind_source:
        enabled: true
      mysql.row_locks:
        enabled: true
      mysql.row_operations:
        enabled: true
      mysql.sorts:
        enabled: true
      mysql.statement_event.count:
        enabled: true
      mysql.statement_event.wait.time:
        enabled: true
      mysql.table.io.wait.count:
        enabled: true
      mysql.table.io.wait.time:
        enabled: true
      mysql.table.lock_wait.count:
        enabled: true
      mysql.table.lock_wait.time:
        enabled: true
      mysql.table_open_cache:
        enabled: true
      mysql.threads:
        enabled: true
      mysql.tmp_resources:
        enabled: true
      mysql.uptime:
        enabled: true

  mysql/replica:
    endpoint: ${env:MYSQL_REPLICA_ENDPOINT}
    username: ${env:MYSQL_USER}
    password: ${env:MYSQL_PASSWORD}
    database: ${env:MYSQL_DATABASE}
    collection_interval: 10s
    initial_delay: 1s
    metrics:
      mysql.replica.time_behind_source:
        enabled: true
      mysql.replica.sql_delay:
        enabled: true
      mysql.buffer_pool.usage:
        enabled: true
      mysql.connection.count:
        enabled: true
      mysql.query.count:
        enabled: true
      mysql.threads:
        enabled: true

  health_check:
    endpoint: 0.0.0.0:13133

processors:
  memory_limiter:
    check_interval: 5s
    limit_percentage: 80
    spike_limit_percentage: 30

  batch:
    send_batch_size: 1000
    timeout: 10s
    send_batch_max_size: 2000

  resource:
    attributes:
      - key: service.name
        value: mysql-monitoring
        action: insert
      - key: service.namespace
        value: ${env:NAMESPACE}
        action: insert
      - key: service.version
        value: ${env:MYSQL_VERSION}
        action: insert
      - key: mysql.instance.endpoint
        value: ${env:MYSQL_PRIMARY_ENDPOINT}
        action: insert
      - key: mysql.instance.role
        value: ${env:MYSQL_ROLE}
        action: insert
      - key: cloud.provider
        value: ${env:CLOUD_PROVIDER}
        action: insert
      - key: cloud.region
        value: ${env:CLOUD_REGION}
        action: insert
      - key: deployment.environment
        value: ${env:ENVIRONMENT}
        action: insert

  attributes/newrelic:
    actions:
      - key: newrelic.source
        value: opentelemetry
        action: insert
      - key: instrumentation.name
        value: mysql-otel-collector
        action: insert
      - key: instrumentation.version
        value: "1.0.0"
        action: insert
      - key: instrumentation.provider
        value: opentelemetry
        action: insert
      - key: db.system
        value: mysql
        action: insert
      - key: environment
        value: ${env:ENVIRONMENT}
        action: insert
      - key: team
        value: ${env:TEAM_NAME}
        action: insert
      - key: cost_center
        value: ${env:COST_CENTER}
        action: insert

  filter/errors:
    error_mode: ignore
    metrics:
      datapoint:
        - 'attributes["error"] == true'

  transform:
    metric_statements:
      - context: metric
        statements:
          - set(attributes["nr.metricType"], "mysql")
          - set(attributes["nr.category"], "database")
      - context: datapoint
        statements:
          - limit(attributes["table"], 100) where metric.name == "mysql.table.io.wait.count"
          - limit(attributes["index"], 100) where metric.name == "mysql.index.io.wait.count"

exporters:
  otlp/newrelic:
    endpoint: ${env:NEW_RELIC_OTLP_ENDPOINT}
    headers:
      api-key: ${env:NEW_RELIC_API_KEY}
    compression: gzip
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s

  logging:
    loglevel: info
    sampling_initial: 5
    sampling_thereafter: 200

  prometheus:
    endpoint: 0.0.0.0:8889
    namespace: mysql

extensions:
  health_check:
    endpoint: 0.0.0.0:13133

  pprof:
    endpoint: 0.0.0.0:1777

  zpages:
    endpoint: 0.0.0.0:55679

service:
  telemetry:
    logs:
      level: info

  extensions: [health_check, pprof, zpages]

  pipelines:
    metrics:
      receivers: [mysql/primary, mysql/replica]
      processors: [memory_limiter, batch, resource, attributes/newrelic, filter/errors, transform]
      exporters: [otlp/newrelic, prometheus, logging]

    traces:
      receivers: []
      processors: [memory_limiter, batch, resource, attributes/newrelic]
      exporters: [otlp/newrelic, logging]