receivers:
  otlp:
    protocols:
      grpc:
        endpoint: localhost:4317
      http:
        endpoint: localhost:4318
  
  # PostgreSQL receiver (using contrib)
  postgresql:
    endpoint: postgres://postgres:postgres@localhost:5432/testdb?sslmode=disable
    collection_interval: 10s
    databases:
      - testdb
    metrics:
      postgresql.database.size:
        enabled: true
      postgresql.table.size:
        enabled: true
      postgresql.rows:
        enabled: true
      postgresql.blocks.read:
        enabled: true
      postgresql.blocks.written:
        enabled: true
      postgresql.commits:
        enabled: true
      postgresql.rollbacks:
        enabled: true
      postgresql.connections:
        enabled: true
      postgresql.backends:
        enabled: true

processors:
  batch:
    timeout: 10s
    send_batch_size: 1024
  
  memory_limiter:
    check_interval: 5s
    limit_percentage: 80
    spike_limit_percentage: 20

  # Add custom processors when they're registered
  # adaptivesampler:
  #   base_rate: 0.1
  #   adjustment_factor: 0.05
  #   min_rate: 0.01
  #   max_rate: 1.0
  
  # circuitbreaker:
  #   failure_threshold: 5
  #   recovery_timeout: 30s
  #   consecutive_failures: 3

exporters:
  debug:
    verbosity: detailed
    sampling_initial: 5
    sampling_thereafter: 200
  
  otlp:
    endpoint: localhost:4318
    tls:
      insecure: true

  # File exporter for analysis
  file:
    path: ./e2e-test-metrics.json
    rotation:
      max_megabytes: 10
      max_days: 3
      max_backups: 3
      localtime: false

service:
  telemetry:
    logs:
      level: info
      development: true
      encoding: console
    metrics:
      level: detailed
      address: localhost:8888

  pipelines:
    metrics/postgresql:
      receivers: [postgresql]
      processors: [memory_limiter, batch]
      exporters: [debug, file]
    
    metrics/otlp:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [debug, file]
    
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [debug]
    
    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [debug]
