apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
  namespace: database-intelligence
type: Opaque
stringData:
  # PostgreSQL credentials
  postgres-host: "postgres-primary.database.svc.cluster.local"
  postgres-port: "5432"
  postgres-user: "monitor"
  postgres-password: "CHANGE_ME_POSTGRES_PASSWORD"
  postgres-database: "production"
  
  # MySQL credentials
  mysql-host: "mysql-primary.database.svc.cluster.local"
  mysql-port: "3306"
  mysql-user: "monitor"
  mysql-password: "CHANGE_ME_MYSQL_PASSWORD"
  mysql-database: "production"
  
  # New Relic credentials
  new-relic-license-key: "CHANGE_ME_NEW_RELIC_LICENSE_KEY"
  new-relic-otlp-endpoint: "https://otlp.nr-data.net:4318"