version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: replication-mysql
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: testdb
    ports:
      - "3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    
  replication-monitor:
    # WARNING: DO NOT ADD healthcheck section here!
    # Health checks have been intentionally removed from production Docker configs.
    
    image: otel/opentelemetry-collector-contrib:latest
    container_name: replication-monitor-otel
    command: ["--config", "/etc/otel/${COLLECTOR_CONFIG:-collector-simple.yaml}"]
    environment:
      MODULE_NAME: replication-monitor
      MYSQL_ENDPOINT: mysql:3306
      MYSQL_USER: root
      MYSQL_PASSWORD: test
      EXPORT_PORT: 8086
      OTEL_SERVICE_NAME: replication-monitor
      # New Relic Configuration
      NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY}
      NEW_RELIC_OTLP_ENDPOINT: ${NEW_RELIC_OTLP_ENDPOINT}
      NEW_RELIC_ACCOUNT_ID: ${NEW_RELIC_ACCOUNT_ID}
      NEW_RELIC_API_KEY: ${NEW_RELIC_API_KEY}
      ENVIRONMENT: production
      CLUSTER_NAME: database-intelligence-cluster
    volumes:
      - ./config:/etc/otel:ro
      - ./logs:/tmp/logs
    ports:
      - "8086:8086"   # Module export port
      - "8896:8889"   # Prometheus exporter
      - "4327:4317"   # OTLP gRPC receiver (unique port)
      - "4328:4318"   # OTLP HTTP receiver (unique port)
      - "55684:55679" # ZPages
      - "1780:1777"   # pprof
      # WARNING: DO NOT expose port 13133 (health check port)!
    depends_on:
      mysql:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'