apiVersion: v1
kind: Secret
metadata:
  name: db-intelligence-secrets
  namespace: db-intelligence
type: Opaque
stringData:
  PG_REPLICA_DSN: "your-postgres-replica-dsn"
  MYSQL_READONLY_DSN: "your-mysql-readonly-dsn"
  NEW_RELIC_LICENSE_KEY: "your-new-relic-license-key"
  OTLP_ENDPOINT: "https://otlp.nr-data.net:4317"