# Single-Instance Kubernetes Deployment for Database Intelligence MVP
# Simplified deployment without Redis dependency for reliable operation
apiVersion: v1
kind: Namespace
metadata:
  name: db-intelligence
  labels:
    app: db-intelligence
    monitoring: enabled
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: db-intelligence
data:
  collector.yaml: |
    # Reference to collector.yaml
    # This would be populated by your CI/CD or Helm
---
apiVersion: v1
kind: Secret
metadata:
  name: db-intelligence-secrets
  namespace: db-intelligence
type: Opaque
stringData:
  new-relic-license-key: "${NEW_RELIC_LICENSE_KEY}"
  pg-replica-dsn: "${PG_REPLICA_DSN}"
  mysql-readonly-dsn: "${MYSQL_READONLY_DSN}"
---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: db-intelligence
  labels:
    app: otel-collector
spec:
  selector:
    app: otel-collector
  ports:
    - name: health
      port: 13133
      targetPort: 13133
    - name: metrics
      port: 8888
      targetPort: 8888
    - name: zpages
      port: 55679
      targetPort: 55679
---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector-headless
  namespace: db-intelligence
  labels:
    app: otel-collector
spec:
  clusterIP: None
  selector:
    app: otel-collector
  ports:
    - name: health
      port: 13133
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: otel-collector-pdb
  namespace: db-intelligence
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: otel-collector
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: otel-collector
  namespace: db-intelligence
  labels:
    app: otel-collector
spec:
  serviceName: otel-collector-headless
  replicas: 1
  selector:
    matchLabels:
      app: otel-collector
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: otel-collector
        version: "2.0.0"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8888"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: otel-collector
      
      # No anti-affinity needed for single instance
            
      # Security context
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        fsGroup: 10001
        
      # Init container to validate configuration
      
          
      containers:
      - name: otel-collector
        image: otel/opentelemetry-collector-contrib:0.89.0
        imagePullPolicy: IfNotPresent
        
        command:
        - /otelcol-contrib
        - --config=/etc/otel/collector.yaml
        
        env:
        - name: GOMEMLIMIT
          value: "460MiB"
        - name: GOGC
          value: "80"
        - name: GOMAXPROCS
          value: "2"
        - name: NEW_RELIC_LICENSE_KEY
          valueFrom:
            secretKeyRef:
              name: db-intelligence-secrets
              key: new-relic-license-key
        - name: OTLP_ENDPOINT
          value: "https://otlp.nr-data.net:4318"
        - name: PG_REPLICA_DSN
          valueFrom:
            secretKeyRef:
              name: db-intelligence-secrets
              key: pg-replica-dsn
        - name: MYSQL_READONLY_DSN
          valueFrom:
            secretKeyRef:
              name: db-intelligence-secrets
              key: mysql-readonly-dsn
        - name: DEPLOYMENT_ENV
          value: "production"
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: COLLECTION_INTERVAL_SECONDS
          value: "60"
        - name: QUERY_TIMEOUT_MS
          value: "3000"
        - name: SAMPLING_PERCENTAGE
          value: "25"
        - name: LOG_LEVEL
          value: "info"
        - name: PG_HOST
          value: "postgres-primary"
        - name: PG_PORT
          value: "5432"
        - name: PG_USER
          value: "postgres"
        - name: PG_PASSWORD
          value: "postgres123"
        - name: PG_DATABASE
          value: "testdb"
        - name: MYSQL_HOST
          value: "mysql-primary"
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_PASSWORD
          value: "mysql123"
        - name: MYSQL_DATABASE
          value: "testdb"
        
        ports:
        - name: health
          containerPort: 13133
        - name: metrics
          containerPort: 8888
        - name: zpages
          containerPort: 55679
          
        # Health checks
        livenessProbe:
          httpGet:
            path: /
            port: health
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
          
        readinessProbe:
          httpGet:
            path: /
            port: health
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
          
        # Resource limits
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
            
        # Volume mounts
        volumeMounts:
        - name: config-collector
          mountPath: /etc/otel/collector.yaml
          subPath: collector.yaml
        - name: config-attribute-mapping
          mountPath: /etc/otel/attribute-mapping.yaml
          subPath: attribute-mapping.yaml
        - name: file-storage
          mountPath: /var/lib/otel
        - name: logs
          mountPath: /var/log
          
      
          
      volumes:
      - name: config-collector
        configMap:
          name: otel-collector-config-collector
      - name: config-attribute-mapping
        configMap:
          name: otel-collector-config-attribute-mapping
          
      - name: logs
        emptyDir: {}
        
  # Persistent storage for file_storage extension
  volumeClaimTemplates:
  - metadata:
      name: file-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: otel-collector
  namespace: db-intelligence
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: otel-collector
rules:
- apiGroups: [""]
  resources: ["nodes", "pods", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets", "daemonsets", "replicasets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otel-collector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: otel-collector
subjects:
- kind: ServiceAccount
  name: otel-collector
  namespace: db-intelligence
---
apiVersion: v1
kind: Service
metadata:
  name: db-intelligence-leader
  namespace: db-intelligence
spec:
  selector:
    app: otel-collector
  ports:
  - name: leader-http
    port: 4040
    targetPort: 4040
---
# HorizontalPodAutoscaler for scaling based on load
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: otel-collector-hpa
  namespace: db-intelligence
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: otel-collector
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
---
# NetworkPolicy for security
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: otel-collector-network-policy
  namespace: db-intelligence
spec:
  podSelector:
    matchLabels:
      app: otel-collector
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: monitoring
    ports:
    - protocol: TCP
      port: 8888  # Metrics
    - protocol: TCP
      port: 13133 # Health
  egress:
  # Allow DNS
  - to:
    - namespaceSelector: {}
      podSelector:
        matchLabels:
          k8s-app: kube-dns
    ports:
    - protocol: UDP
      port: 53
  # Allow New Relic endpoint
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
    ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 4318
  # Allow database connections
  - to:
    - ipBlock:
        cidr: 10.0.0.0/8  # Adjust for your database network
    ports:
    - protocol: TCP
      port: 5432  # PostgreSQL
    - protocol: TCP
      port: 3306  # MySQL
