apiVersion: v1
kind: ServiceAccount
metadata:
  name: database-intelligence-collector
  namespace: database-intelligence
  labels:
    app.kubernetes.io/name: database-intelligence
    app.kubernetes.io/component: serviceaccount
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: database-intelligence-collector
  namespace: database-intelligence
  labels:
    app.kubernetes.io/name: database-intelligence
    app.kubernetes.io/component: rbac
rules:
  # Allow reading config maps for dynamic configuration
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
  # Allow reading secrets for credentials
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
  # Allow reading pods for metadata
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  # Allow reading services for discovery
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list"]
  # Allow reading endpoints for service discovery
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: database-intelligence-collector
  namespace: database-intelligence
  labels:
    app.kubernetes.io/name: database-intelligence
    app.kubernetes.io/component: rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: database-intelligence-collector
subjects:
  - kind: ServiceAccount
    name: database-intelligence-collector
    namespace: database-intelligence