receivers:
  postgresql:
    endpoint: localhost:5432
    username: postgres
    password: postgres
    databases:
      - postgres
    collection_interval: 10s
    tls:
      insecure: true
    
  mysql:
    endpoint: localhost:3306
    username: root
    password: mysql
    database: mysql
    collection_interval: 10s
    tls:
      insecure: true

processors:
  batch:
    timeout: 1s
    send_batch_size: 100

exporters:
  debug:
    verbosity: detailed
    sampling_initial: 10
    sampling_thereafter: 100

extensions:
  health_check:
    endpoint: 0.0.0.0:13133

service:
  extensions: [health_check]
  pipelines:
    metrics/postgresql:
      receivers: [postgresql]
      processors: [batch]
      exporters: [debug]
    metrics/mysql:
      receivers: [mysql]
      processors: [batch]
      exporters: [debug]

  telemetry:
    logs:
      level: debug