receivers:
  otlp:
    protocols:
      grpc:
        endpoint: localhost:4317
      http:
        endpoint: localhost:4318

processors:
  batch:
    timeout: 10s
  
  # Custom processors
  adaptivesampler:
    sampling_percentage: 50
  
  circuitbreaker:
    failure_threshold: 5
    timeout: 30s

exporters:
  debug:
    verbosity: detailed
  
  otlphttp/newrelic:
    endpoint: https://otlp.nr-data.net
    headers:
      api-key: ${NEW_RELIC_API_KEY}

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [adaptivesampler, circuitbreaker, batch]
      exporters: [debug, otlphttp/newrelic]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlphttp/newrelic]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlphttp/newrelic]
